import React, { useState } from "react";
import { Flame, ShieldAlert, X, Send, MapPin } from "lucide-react";
import { Hotspot } from "../types";

interface CreateHotspotModalProps {
  isOpen: boolean;
  onClose: () => void;
  onHotspotCreated: (hotspot: Hotspot) => void;
}

export default function CreateHotspotModal({ isOpen, onClose, onHotspotCreated }: CreateHotspotModalProps) {
  const [name, setName] = useState("Kandla Port Chemical Storage");
  const [region, setRegion] = useState("Gujarat Coastal Corridor");
  const [coordinates, setCoordinates] = useState("23.0031° N, 70.2184° E");
  const [meanFRP, setMeanFRP] = useState("280");
  const [severity, setSeverity] = useState<"CRITICAL" | "HIGH RISK" | "MODERATE">("CRITICAL");
  const [isSubmitting, setIsSubmitting] = useState(false);

  if (!isOpen) return null;

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);

    const frp = parseFloat(meanFRP) || 200;
    const riskScore = severity === "CRITICAL" ? 82.5 : severity === "HIGH RISK" ? 58.0 : 35.0;

    const newHotspot: Hotspot = {
      id: `EVT-${new Date().toISOString().slice(0, 10).replace(/-/g, "")}-${Math.floor(1000 + Math.random() * 9000)}`,
      name,
      region,
      coordinates,
      priority: severity === "CRITICAL" ? "HIGH-ASSET" : "MODERATE-ASSET",
      severity,
      riskScore,
      detectedAt: new Date().toISOString().replace("T", " ").slice(0, 19) + " UTC",
      meanFRP: frp,
      peakFRP: frp * 1.25,
      distanceToAsset: "380m",
      assetType: "Petrochemical Bulk Terminal",
      osmIdentifier: `way/${Math.floor(10000000 + Math.random() * 90000000)}`,
      roadAccess: "180m (Expressway Link)",
      nearestFireStation: "3.5 km (Port Authority)",
      terrainCover: "Industrial Concrete / Coastal",
      activeFlameProb: severity === "CRITICAL" ? 94.0 : 76.0,
      refineryProximityProb: 89.0,
      persistenceIndex: 68.0,
      detections30d: 12,
      detections90d: 31,
      trend30d: "+8.4 MW/wk",
      sensors: ["VIIRS-FRP", "SENTINEL-L2A", "OSM-GEO"],
      ndvi: -0.15,
      nbr: 0.65,
      ndmi: 0.38,
      swirNir: 2.45,
      formula: "0.45(P_fire) + 0.35(P_ind) + 0.20(P_pers) = " + riskScore,
      defaultSummary: `Manual tactical alert generated by operator for ${name}. High thermal reading of ${frp} MW observed near bulk fuel infrastructure.`,
      recommendation: "Deploy nearest industrial foam suppression tender and notify Port Operations Center."
    };

    // Save hotspot and report to backend
    try {
      await fetch("/api/hotspots", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(newHotspot)
      });

      await fetch("/api/reports", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          hotspotId: newHotspot.id,
          facilityName: newHotspot.name,
          region: newHotspot.region,
          severity: newHotspot.severity,
          riskScore: newHotspot.riskScore,
          dispatchPriority: "ALPHA",
          targetAgency: "District Disaster Management & State Fire Command",
          summary: newHotspot.defaultSummary,
          recommendation: newHotspot.recommendation
        })
      });
    } catch (e) {
      console.warn("Backend dispatch sync:", e);
    }

    onHotspotCreated(newHotspot);
    setIsSubmitting(false);
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/75 backdrop-blur-sm animate-in fade-in duration-150">
      <div className="relative w-full max-w-lg p-6 rounded-2xl bg-[#0f172a] border border-[#1e2c4a] shadow-2xl text-white">
        
        {/* Header */}
        <div className="flex items-center justify-between pb-4 border-b border-[#1e2c4a]">
          <div className="flex items-center gap-2.5">
            <div className="p-2 rounded-xl bg-rose-500/15 border border-rose-500/30 text-rose-400">
              <Flame className="h-5 w-5 fill-rose-500" />
            </div>
            <div>
              <h2 className="text-sm font-bold tracking-tight text-white">
                Dispatch New Thermal Anomaly Alert
              </h2>
              <p className="text-[11px] text-slate-400">
                Manual Satellite Telemetry Override &amp; Tasking
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition-colors"
          >
            <X className="h-4 w-4" />
          </button>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit} className="mt-4 flex flex-col gap-3.5 text-xs">
          <div>
            <label className="font-semibold text-slate-300">Facility / Target Asset Name</label>
            <input
              type="text"
              value={name}
              onChange={(e) => setName(e.target.value)}
              required
              className="mt-1 w-full px-3.5 py-2 rounded-xl bg-[#10172a] border border-[#1e2c4a] text-slate-200 focus:outline-none focus:ring-2 focus:ring-rose-500"
            />
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="font-semibold text-slate-300">Defense Corridor / Region</label>
              <input
                type="text"
                value={region}
                onChange={(e) => setRegion(e.target.value)}
                required
                className="mt-1 w-full px-3.5 py-2 rounded-xl bg-[#10172a] border border-[#1e2c4a] text-slate-200 focus:outline-none focus:ring-2 focus:ring-rose-500"
              />
            </div>
            <div>
              <label className="font-semibold text-slate-300">Geospatial Coordinates</label>
              <input
                type="text"
                value={coordinates}
                onChange={(e) => setCoordinates(e.target.value)}
                required
                className="mt-1 w-full px-3.5 py-2 rounded-xl bg-[#10172a] border border-[#1e2c4a] text-slate-200 focus:outline-none focus:ring-2 focus:ring-rose-500"
              />
            </div>
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="font-semibold text-slate-300">Radiant Power (Mean FRP in MW)</label>
              <input
                type="number"
                value={meanFRP}
                onChange={(e) => setMeanFRP(e.target.value)}
                required
                className="mt-1 w-full px-3.5 py-2 rounded-xl bg-[#10172a] border border-[#1e2c4a] text-slate-200 focus:outline-none focus:ring-2 focus:ring-rose-500"
              />
            </div>
            <div>
              <label className="font-semibold text-slate-300">Severity Tier</label>
              <select
                value={severity}
                onChange={(e) => setSeverity(e.target.value as any)}
                className="mt-1 w-full px-3.5 py-2 rounded-xl bg-[#10172a] border border-[#1e2c4a] text-slate-200 focus:outline-none focus:ring-2 focus:ring-rose-500"
              >
                <option value="CRITICAL">CRITICAL (Alpha Priority)</option>
                <option value="HIGH RISK">HIGH RISK (Bravo Priority)</option>
                <option value="MODERATE">MODERATE (Monitoring)</option>
              </select>
            </div>
          </div>

          <button
            type="submit"
            disabled={isSubmitting}
            className="mt-3 w-full py-2.5 rounded-xl bg-rose-600 hover:bg-rose-700 text-white font-semibold transition-colors flex items-center justify-center gap-2 cursor-pointer shadow-lg shadow-rose-900/30 disabled:opacity-50"
          >
            <Send className="h-4 w-4" />
            <span>Broadcast &amp; Dispatch Tactical Dossier</span>
          </button>
        </form>
      </div>
    </div>
  );
}
