import { HotspotRecord } from "../models/hotspot.model.js";
import { AuditRecord } from "../models/audit.model.js";
import { IncidentReportRecord } from "../models/report.model.js";

/**
 * Benchmark Hotspot Telemetry Dataset
 * Calibrated with real multispectral bands (Sentinel-2 L2A & VIIRS FRP).
 */
export const INITIAL_HOTSPOTS: HotspotRecord[] = [
  {
    id: "EVT-20260903-0042",
    name: "Paradip Coastal Petrochemical Enclave",
    region: "Odisha Industrial Corridor",
    coordinates: "20.1234° N, 85.7654° E",
    priority: "HIGH-ASSET",
    severity: "CRITICAL",
    riskScore: 78.4,
    detectedAt: "2026-09-03 14:18:22 UTC",
    meanFRP: 342.0,
    peakFRP: 418.5,
    distanceToAsset: "412m",
    assetType: "Hydrocarbon Refining",
    osmIdentifier: "way/94827104",
    roadAccess: "120m (SH-12 Link)",
    nearestFireStation: "4.2 km (Paradip Port)",
    terrainCover: "Hardened Asphalt / Metal",
    activeFlameProb: 91.2,
    refineryProximityProb: 88.5,
    persistenceIndex: 72.0,
    detections30d: 18,
    detections90d: 47,
    trend30d: "+12.3 MW/wk",
    sensors: ["VIIRS-FRP", "OSM-GEO", "SENTINEL-L2A", "TEMPORAL-REC"],
    ndvi: -0.18,
    nbr: 0.74,
    ndmi: 0.42,
    swirNir: 2.81,
    formula: "0.45(P_fire) + 0.35(P_ind) + 0.20(P_pers) = 78.4",
    defaultSummary: "This event is classified as CRITICAL with a risk score of 78.4/100. Key telemetry: FRP mean of 342 MW at 412m proximity to a known oil refinery inside the designated Odisha Industrial Corridor. Temporal analysis reveals 18 detections in 30 days with a positive upward slope (+12.3 MW/week). ConvNeXt-Tiny multispectral classification confirms Active Industrial Fire with 91.2% confidence. Simulated Grad-CAM analysis isolates thermal activation concentrated directly on processing units rather than open flare pits.",
    recommendation: "Recommend immediate site verification and priority alert to refinery safety dispatch. Notify District Emergency Ops Center (DEOC)."
  },
  {
    id: "EVT-20260903-0089",
    name: "Dahej Special Economic Chemical Zone",
    region: "Gujarat Petrochem Belt",
    coordinates: "21.7051° N, 72.5857° E",
    priority: "HIGH-ASSET",
    severity: "HIGH RISK",
    riskScore: 51.2,
    detectedAt: "2026-09-03 13:42:10 UTC",
    meanFRP: 144.0,
    peakFRP: 162.0,
    distanceToAsset: "1,302m",
    assetType: "Specialty Polymer Plant",
    osmIdentifier: "way/72891244",
    roadAccess: "240m (GIDC Avenue 2)",
    nearestFireStation: "6.8 km (Dahej Fire Station)",
    terrainCover: "Soil / Sparsely Vegetated",
    activeFlameProb: 84.6,
    refineryProximityProb: 55.2,
    persistenceIndex: 44.0,
    detections30d: 9,
    detections90d: 22,
    trend30d: "+4.1 MW/wk",
    sensors: ["VIIRS-FRP", "OSM-GEO", "SENTINEL-L2A"],
    ndvi: 0.12,
    nbr: 0.38,
    ndmi: 0.15,
    swirNir: 1.65,
    formula: "0.45(P_fire) + 0.35(P_ind) + 0.20(P_pers) = 51.2",
    defaultSummary: "This event is flagged as HIGH RISK with a deterministic risk score of 51.2/100. Active flame probability is estimated at 84.6%, operating at a distance of 1,302m from primary chemical storage facilities. Historical 30-day recurrence remains moderate with 9 detections. SWIR-based indices suggest active surface carbonization but less intense radiant power output compared to the Odisha refinery crisis.",
    recommendation: "Issue preventative advisory warning to site supervisors. Increase monitoring rate to 15-minute Sentinel-2 pre-pass tasking."
  },
  {
    id: "EVT-20260902-0031",
    name: "Jharkhand Steel Cluster",
    region: "Jamshedpur Industrial Zone",
    coordinates: "22.7925° N, 86.1842° E",
    priority: "MODERATE-ASSET",
    severity: "MODERATE",
    riskScore: 34.2,
    detectedAt: "2026-09-02 09:12:44 UTC",
    meanFRP: 94.5,
    peakFRP: 110.0,
    distanceToAsset: "1,800m",
    assetType: "Blast Furnace Area",
    osmIdentifier: "way/10492812",
    roadAccess: "500m (Industrial Link)",
    nearestFireStation: "8.1 km (Jamshedpur Sector 4)",
    terrainCover: "Concrete / Built-up",
    activeFlameProb: 52.0,
    refineryProximityProb: 24.1,
    persistenceIndex: 31.0,
    detections30d: 5,
    detections90d: 14,
    trend30d: "+0.8 MW/wk",
    sensors: ["VIIRS-FRP", "SENTINEL-L2A"],
    ndvi: 0.04,
    nbr: 0.15,
    ndmi: 0.08,
    swirNir: 1.10,
    formula: "0.45(P_fire) + 0.35(P_ind) + 0.20(P_pers) = 34.2",
    defaultSummary: "An anomaly detected in Jharkhand Steel Cluster with a score of 34.2/100 (MODERATE). Highly localized slag dump thermal flare activity, located roughly 1.8km away from core structures. High stability index and low 30-day trend indicate normal operational cooling cycles.",
    recommendation: "Log event to general audit log. Standard automatic tracking. No tactical deployment needed."
  },
  {
    id: "EVT-20260902-0012",
    name: "Nagpur Logistics Hub",
    region: "Maharashtra Central Corridor",
    coordinates: "21.1458° N, 79.0882° E",
    priority: "LOW-ASSET",
    severity: "MONITORED",
    riskScore: 18.1,
    detectedAt: "2026-09-02 04:30:15 UTC",
    meanFRP: 31.2,
    peakFRP: 45.0,
    distanceToAsset: "3,200m",
    assetType: "Agricultural Storage Yards",
    osmIdentifier: "way/59827110",
    roadAccess: "1.2 km (National Highway)",
    nearestFireStation: "12.0 km (Nagpur Rural)",
    terrainCover: "Cropland / Bare Soil",
    activeFlameProb: 15.4,
    refineryProximityProb: 5.0,
    persistenceIndex: 12.0,
    detections30d: 2,
    detections90d: 3,
    trend30d: "-2.4 MW/wk",
    sensors: ["VIIRS-FRP"],
    ndvi: 0.45,
    nbr: 0.05,
    ndmi: -0.12,
    swirNir: 0.65,
    formula: "0.45(P_fire) + 0.35(P_ind) + 0.20(P_pers) = 18.1",
    defaultSummary: "Low severity hotspot observed near Nagpur Logistics Hub, scoring 18.1/100 (MONITORED). Class 4 anomaly indicative of minor biomass residue controlled agricultural burning. Rapidly decaying thermal signature.",
    recommendation: "No operational response needed. Flagged as seasonal agricultural stubble clearing."
  }
];

export const INITIAL_AUDIT_LOGS: AuditRecord[] = [
  {
    id: "aud-001",
    block: 104291,
    hash: "0x8fa12ce973bd540191fe8c9321aa",
    event: "EVT-20260903-0042",
    action: "Multispectral Sentinel-2 L2A Ingestion",
    source: "Sentinel-2 MSI Level-2A",
    timestamp: "2026-09-03 14:18:22 UTC",
    status: "VERIFIED"
  },
  {
    id: "aud-002",
    block: 104290,
    hash: "0x3da94a619c00bcf955ab331201dd",
    event: "EVT-20260903-0042",
    action: "VIIRS Active Fire Ingestion (FRP 342MW)",
    source: "VIIRS I-Band (NOAA-20)",
    timestamp: "2026-09-03 14:10:00 UTC",
    status: "VERIFIED"
  },
  {
    id: "aud-003",
    block: 104289,
    hash: "0xe21ba40982bbfe39118c642289aa",
    event: "EVT-20260903-0089",
    action: "Hazardous Chemical Proximity Verification",
    source: "Sentinel-2 MSI Level-2A",
    timestamp: "2026-09-03 13:42:10 UTC",
    status: "VERIFIED"
  },
  {
    id: "aud-004",
    block: 104288,
    hash: "0xbcd91264ac19318844fe015389bb",
    event: "EVT-20260903-0089",
    action: "VIIRS Ingestion & Initial Risk Computation",
    source: "VIIRS I-Band (Suomi-NPP)",
    timestamp: "2026-09-03 13:35:00 UTC",
    status: "VERIFIED"
  }
];

export const INITIAL_REPORTS: IncidentReportRecord[] = [
  {
    id: "DOSSIER-20260903-001",
    hotspotId: "EVT-20260903-0042",
    facilityName: "Paradip Coastal Petrochemical Enclave",
    region: "Odisha Industrial Corridor",
    severity: "CRITICAL",
    riskScore: 78.4,
    detectedAt: "2026-09-03 14:18:22 UTC",
    dispatchedAt: "2026-09-03 14:24:00 UTC",
    dispatchPriority: "ALPHA",
    targetAgency: "District Emergency Operations Center (DEOC) & Paradip Port Fire Authority",
    summary: "Critical thermal signature (342 MW mean FRP) detected within 412m of hydrocarbon cracking tanks. Persistence index at 72% across 30 days.",
    recommendation: "Immediate aerial surveillance and deployment of Class B thermal suppression foam units to perimeter road SH-12.",
    status: "DISPATCHED"
  },
  {
    id: "DOSSIER-20260903-002",
    hotspotId: "EVT-20260903-0089",
    facilityName: "Dahej Special Economic Chemical Zone",
    region: "Gujarat Petrochem Belt",
    severity: "HIGH RISK",
    riskScore: 51.2,
    detectedAt: "2026-09-03 13:42:10 UTC",
    dispatchedAt: "2026-09-03 13:50:00 UTC",
    dispatchPriority: "BRAVO",
    targetAgency: "GIDC Industrial Safety Inspectorate",
    summary: "High-temperature flaring outside scheduled refinery maintenance hours. Proximity to polymer feedstock depot: 1,302m.",
    recommendation: "Issue high-level advisory warning to on-duty plant safety director; monitor for fugitive emissions.",
    status: "ACKNOWLEDGED"
  }
];

export function mapRowToHotspot(row: any): HotspotRecord {
  return {
    id: row.id,
    name: row.name,
    region: row.region,
    coordinates: row.coordinates,
    priority: row.priority,
    severity: row.severity,
    riskScore: Number(row.risk_score),
    detectedAt: row.detected_at,
    meanFRP: Number(row.mean_frp),
    peakFRP: Number(row.peak_frp),
    distanceToAsset: row.distance_to_asset,
    assetType: row.asset_type,
    osmIdentifier: row.osm_identifier,
    roadAccess: row.road_access,
    nearestFireStation: row.nearest_fire_station,
    terrainCover: row.terrain_cover,
    activeFlameProb: Number(row.active_flame_prob),
    refineryProximityProb: Number(row.refinery_proximity_prob),
    persistenceIndex: Number(row.persistence_index),
    detections30d: Number(row.detections_30d),
    detections90d: Number(row.detections90d ?? row.detections_90d),
    trend30d: row.trend_30d,
    sensors: typeof row.sensors === "string" ? JSON.parse(row.sensors) : (row.sensors || []),
    ndvi: Number(row.ndvi),
    nbr: Number(row.nbr),
    ndmi: Number(row.ndmi),
    swirNir: Number(row.swir_nir),
    formula: row.formula,
    defaultSummary: row.default_summary,
    recommendation: row.recommendation,
  };
}

export function mapRowToAudit(row: any): AuditRecord {
  return {
    id: row.id,
    block: Number(row.block_num),
    hash: row.hash,
    event: row.event,
    action: row.action,
    source: row.source,
    timestamp: row.timestamp,
    status: row.status,
  };
}

export function mapRowToReport(row: any): IncidentReportRecord {
  return {
    id: row.id,
    hotspotId: row.hotspot_id,
    facilityName: row.facility_name,
    region: row.region,
    severity: row.severity,
    riskScore: Number(row.risk_score),
    detectedAt: row.detected_at,
    dispatchedAt: row.dispatched_at,
    dispatchPriority: row.dispatch_priority,
    targetAgency: row.target_agency,
    summary: row.summary,
    recommendation: row.recommendation,
    status: row.status,
  };
}
